workflows:
  android-apk:
    name: Android APK

    environment:
      java: 17

    scripts:
      - python3 -m pip install --upgrade pip
      - pip install buildozer cython
      - yes | sdkmanager --licenses
      - buildozer android debug

    artifacts:
      - bin/*.apk
