workflows:
  android-apk:
    name: Android APK

    environment:
      vars:
        BUILDOZER_WARN_ON_ROOT: 1

    scripts:
      - python3 -m pip install --upgrade pip
      - pip3 install buildozer cython
      - buildozer android debug

    artifacts:
      - bin/*.apk
